// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAThrmtrqZPth0KjLBWfYFsgvvT0orTHg',
    appId: '1:419376172089:web:17b93ba190845a1fd351e8',
    messagingSenderId: '419376172089',
    projectId: 'exam-96584',
    authDomain: 'exam-96584.firebaseapp.com',
    storageBucket: 'exam-96584.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA63IAqOgbanTqTszahCl4ByZKMhrcljmE',
    appId: '1:419376172089:android:73952f16c359cea6d351e8',
    messagingSenderId: '419376172089',
    projectId: 'exam-96584',
    storageBucket: 'exam-96584.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcQB3518BJdv0QrH6A7M6_HR6c7IgaRR8',
    appId: '1:419376172089:ios:69b189880f40c633d351e8',
    messagingSenderId: '419376172089',
    projectId: 'exam-96584',
    storageBucket: 'exam-96584.appspot.com',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcQB3518BJdv0QrH6A7M6_HR6c7IgaRR8',
    appId: '1:419376172089:ios:ed7148b70011268cd351e8',
    messagingSenderId: '419376172089',
    projectId: 'exam-96584',
    storageBucket: 'exam-96584.appspot.com',
    iosBundleId: 'com.example.exam.RunnerTests',
  );
}
